### ISSUE TITLE
Unable to run the jar file build for android

### ISSUE THREAD

**Issue by Praveenjohn50** [apertium/lttoolbox-java#1]
When i tried to run the jar file of the language pair.The following error message is displayed as "Cannot run cg-proc" and cannot run lrx-proc.

**Comment by nordfalk** [comment]
This is because cg-proc (Contraint Grammar) and lrx-proc isnt implementet in lttoolbox-java. 
Therefore lttoolbox-java tries to execute them as external commands, and that fails as they arent available on Android.
