### ISSUE TITLE
Doesn't build on latest Debian

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/lttoolbox-java#4]
From https://apertium.projectjj.com/apt/logs/lttoolbox-java/sid-amd64.log, and many others like it:
````
    [javac] /build/lttoolbox-java-3.2.0+g744~b0fbd3b0-1~sid1/src/org/apertium/transfer/generation/TransferBytecode.java:7: error: cannot find symbol
    [javac] import static com.sun.org.apache.bcel.internal.Constants.ACC_PRIVATE;
    [javac]                                               ^
    [javac]   symbol:   class Constants
    [javac]   location: package com.sun.org.apache.bcel.internal
````

Doesn't help to install `libbcel-java`

**Comment by nordfalk** [comment]
I'll try to have a look in the coming weeks

**Comment by nordfalk** [comment]
These packages doesent exists in Java 11 and onward.
Perhaps @artetxem have an idea on how to proceed on this one?
For now, please use Java 8 for compilation. 
Probably the conversion of transfer files to Java bytecode doesent work anymore in Java 11. The rest should work in Java 11.

**Comment by niccottrell** [comment]
It looks like Constants was deprecated and it might just be enough to change all usages of `com.sun.org.apache.bcel.internal.Constants` to `com.sun.org.apache.bcel.internal.Const`

See https://commons.apache.org/proper/commons-bcel/apidocs/org/apache/bcel/Const.html

**Comment by nordfalk** [comment]
Thanks @niccottrell  it seems you are right.

These need to be replaced as well - any idea with which?
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.ARRAYLENGTH;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.DUP;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.ICONST_0;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.ICONST_1;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.IRETURN;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.ISUB;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.NOP;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.POP;
import static com.sun.org.apache.bcel.internal.generic.InstructionConstants.RETURN;

It seems they are in https://commons.apache.org/proper/commons-bcel/apidocs/org/apache/bcel/generic/InstructionConst.html  ... so including https://commons.apache.org/proper/commons-bcel/ as a dependency might be the right way to go.

Any thoughts @artetxem ?

**Comment by niccottrell** [comment]
I believe the commons-bcel dependency is only required is we move from `com.sun.org.apache.bcel.internal.generic` to `org.apache.bcel.internal.generic` package. 

So I think `com.sun.org.apache.bcel.internal.generic.InstructionConstants` can be just changed to `com.sun.org.apache.bcel.internal.generic.InstructionConst` and no other dependency change is needed.

**Comment by TinoDidriksen** [comment]
Still doesn't build with `openjdk-8-jdk-headless` - same errors. Also same with both `openjdk-8-jdk-headless` and `libbcel-java`.

I need it to build with only Debian Sid (unstable) packages. Can't rely on 3rd party dependencies or tools, unless they're bundled in this package.

**Comment by nordfalk** [comment]
Tino, it works for me with openjdk-8-jdk-headless (I dont need libbcel-java). 

I can see from the log (https://apertium.projectjj.com/apt/logs/lttoolbox-java/sid-amd64.log) that you install openjdk-11-jdk-headless as well.
Try with:

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
make clean
make

I get a lot of ' warning: Type is internal proprietary API and may be removed in a future release' .... but it compiles and dist/lttoolbox.jar is created after compilation.

**Comment by TinoDidriksen** [comment]
`export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/` was the trick.

The build does not install `openjdk-11-jdk-headless` but it does install `openjdk-11-jre-headless`, though it doesn't need to. But that's what one gets when installing `ant` first or alongside `openjdk-8-jdk-headless`. I had not considered multiple conflicting versions of packages in the build system.

So that solves it for now, but this issue will come back when Java 8 is removed from Debian and other mainline use.
