### ISSUE TITLE
Doesn't build on latest Debian, again

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/lttoolbox-java#6]
The problem from https://github.com/apertium/lttoolbox-java/issues/4#issuecomment-543759870 is now reality. OpenJDK 8 was removed from Debian. Oldest installable release is OpenJDK 11.

**Comment by nordfalk** [comment]
OK. Time to update to new JDK. Whats the newest JDK that Debian currently supports?

**Comment by TinoDidriksen** [comment]
https://packages.debian.org/search?keywords=default-jdk-headless is currently OpenJDK 11 for Debian Sid, but versions up to 17 are available for install.

**Comment by nordfalk** [comment]
Fixed in https://github.com/apertium/lttoolbox-java/commit/5a888db56008c4b70b0aa4c396e5a8279be1753c
